title: 计算社会科学杂记
description: 一个STATA\Python\R语言\Netlogo等软件的学习记录
author: 蒋和超-一个不务正业的社会学学者
github: https://github.com/jhchao
about: 西南财经大学社会发展研究院，社会学博士，硕士生导师.主要研究方向：应用社会学、金融社会学、计算社会学.
disqus_shortname: CSS
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/jhchao"



urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/


url: "https://jhchao.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
